# MiniMax
# Required secrets: CCE_MINIMAX_TOKEN

export ANTHROPIC_BASE_URL="https://api.minimaxi.com/anthropic"
export ANTHROPIC_AUTH_TOKEN="${CCE_MINIMAX_TOKEN:?}"
export ANTHROPIC_MODEL="MiniMax-M3"
export ANTHROPIC_DEFAULT_SONNET_MODEL="MiniMax-M3"
export ANTHROPIC_DEFAULT_OPUS_MODEL="MiniMax-M3"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="MiniMax-M3"
export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_AUTO_COMPACT_WINDOW="512000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
